// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
  KV: KVNamespace;
  TELEGRAM_BOT_TOKEN?: string;
  TELEGRAM_CHAT_IDS?: string;
  FORWARD_TO: string;
  EMAIL_WHITELIST: string;
  CODE_KEYWORDS: string;
  WECOM_BOT_GUID?: string;
}
